// Loads the pg-export SQL files generated by export-sqlite.js into a Postgres/Supabase DB,
// then verifies row counts match the source manifest (zero-loss check).
//
// Usage (run this on YOUR machine, your DB password stays in your terminal only):
//   DATABASE_URL="postgresql://postgres...replace-password..." node scripts/import-pg.js
//
// The export dir defaults to data/pg-export.
const { Client } = require('pg');
const fs = require('node:fs');
const path = require('node:path');

async function main() {
  const conn = process.env.DATABASE_URL;
  if (!conn) {
    console.error('Missing DATABASE_URL. Set it to your Supabase connection string with your password, e.g.\n  DATABASE_URL="postgresql://..." node scripts/import-pg.js');
    process.exit(1);
  }
  const EXPORT = process.env.CRM_EXPORT || path.join(__dirname, '..', 'data', 'pg-export');
  const manifestPath = path.join(EXPORT, 'manifest.json');
  if (!fs.existsSync(manifestPath)) {
    console.error('manifest.json not found. Run scripts/export-sqlite.js first.');
    process.exit(1);
  }
  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));

  console.log('Connecting to Postgres…');
  const client = new Client({ connectionString: conn, ssl: { rejectUnauthorized: false } });
  await client.connect();

  // Disable FK-style safety by truncating in dependency order before import.
  // Tables only reference by TEXT ids (no real FK constraints enforced), so order is cosmetic.
  const order = ['activity_log', 'templates', 'drafts', 'emails', 'leads', 'campaigns', 'settings'];
  for (const t of order) {
    if (manifest[t]) await client.query(`TRUNCATE TABLE "${t}" RESTART IDENTITY CASCADE`);
  }

  console.log('Importing tables…');
  for (const t of order) {
    const info = manifest[t];
    if (!info) continue;
    const file = path.join(EXPORT, `table_${t}.sql`);
    if (!fs.existsSync(file)) { console.warn(`  ${t}: no sql file`); continue; }
    const sql = fs.readFileSync(file, 'utf8');
    if (!sql.trim()) { console.log(`  ${t}: 0 rows (empty)`); continue; }
    // Run statements sequentially so we can count via rowCount.
    let inserted = 0;
    for (const stmt of sql.split('\n').filter((l) => l.trim().startsWith('INSERT'))) {
      const r = await client.query(stmt);
      inserted += r.rowCount;
    }
    console.log(`  ${t}: inserted ${inserted} (source ${info.count})`);
  }

  console.log('\n=== VERIFICATION (zero-loss check) ===');
  let allOk = true;
  for (const [t, info] of Object.entries(manifest)) {
    const { rows } = await client.query(`SELECT COUNT(*)::int AS n FROM "${t}"`);
    const n = rows[0].n;
    const ok = n === info.count;
    if (!ok) allOk = false;
    console.log(`  ${t}: DB=${n}  source=${info.count}  ${ok ? 'OK' : '*** MISMATCH ***'}`);
  }
  console.log(allOk ? '\nAll tables migrated with ZERO LOSS. ✓' : '\n!!! MISMATCH FOUND — do not continue without fixing !!!');
  await client.end();
  if (!allOk) process.exit(1);
}

main().catch((e) => { console.error('Import failed:', e.message); process.exit(1); });