// Loads the pg-export SQL files generated by export-sqlite.js into a Postgres/Supabase DB,
// then verifies row counts match the source manifest (zero-loss check).
//
// Usage (run this on YOUR machine, your DB password stays in your terminal only):
//   DATABASE_URL="postgresql://postgres...replace-password..." node scripts/import-pg.js
//
// The export dir defaults to data/pg-export.
const { Client } = require('pg');
const fs = require('node:fs');
const path = require('node:path');

async function main() {
  const conn = process.env.DATABASE_URL;
  if (!conn) {
    console.error('Missing DATABASE_URL. Set it to your Supabase connection string with your password, e.g.\n  DATABASE_URL="postgresql://..." node scripts/import-pg.js');
    process.exit(1);
  }
  const EXPORT = process.env.CRM_EXPORT || path.join(__dirname, '..', 'data', 'pg-export');
  const manifestPath = path.join(EXPORT, 'manifest.json');
  if (!fs.existsSync(manifestPath)) {
    console.error('manifest.json not found. Run scripts/export-sqlite.js first.');
    process.exit(1);
  }
  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));

  console.log('Connecting to Postgres…');
  const ssl = process.env.PGSSL === 'false' ? false : { rejectUnauthorized: false };
  const client = new Client({ connectionString: conn, ssl });
  await client.connect();

  // Ensure tables exist (idempotent) before truncating — works on a fresh Supabase DB.
  const { SCHEMA_SQL } = require('../src/db');
  await client.query(SCHEMA_SQL);

  // Disable FK-style safety by truncating in dependency order before import.
  // Tables only reference by TEXT ids (no real FK constraints enforced), so order is cosmetic.
  const order = ['activity_log', 'templates', 'drafts', 'emails', 'leads', 'campaigns', 'settings'];
  for (const t of order) {
    if (manifest[t]) await client.query(`TRUNCATE TABLE "${t}" RESTART IDENTITY CASCADE`);
  }

  console.log('Importing tables…');
  const BATCH = parseInt(process.env.CRM_BATCH || '200', 10);
  for (const t of order) {
    const info = manifest[t];
    if (!info) continue;
    const file = path.join(EXPORT, `table_${t}.sql`);
    if (!fs.existsSync(file)) { console.warn(`  ${t}: no sql file`); continue; }
    const sql = fs.readFileSync(file, 'utf8');
    if (!sql.trim()) { console.log(`  ${t}: 0 rows (empty)`); continue; }
    // Combine rows into a few large multi-row INSERTs (single round-trip each),
    // instead of one round-trip per row. Each exported line is one row and uses
    // the same column list, so we can reconstruct batches from the column prefix.
    const cols = info.columns.map((c) => `"${c}"`).join(', ');
    const prefixNoParen = `INSERT INTO "${t}" (${cols}) VALUES `;
    const prefix = `${prefixNoParen}(`;
    const tuples = sql.split('\n').filter((l) => l.trim().startsWith('INSERT'))
      .map((l) => l.slice(prefix.length, l.endsWith(');') ? -2 : -1));
    let inserted = 0;
    for (let i = 0; i < tuples.length; i += BATCH) {
      const chunk = tuples.slice(i, i + BATCH).map((tu) => `(${tu})`).join(', ');
      const r = await client.query(`${prefixNoParen}${chunk};`);
      inserted += r.rowCount;
      process.stdout.write(`  ${t}: ${inserted}/${info.count}\r`);
    }
    console.log(`  ${t}: inserted ${inserted} (source ${info.count})`);
  }

  // TRUNCATE ... RESTART IDENTITY resets each SERIAL sequence to 1, but the rows we just
  // inserted use their original explicit ids — so the sequence must be advanced past the
  // real max id, or the next INSERT (with no id given) will collide with an existing row.
  console.log('\nRealigning SERIAL sequences to imported data…');
  for (const t of ['activity_log', 'drafts', 'templates']) {
    if (!manifest[t]) continue;
    const r = await client.query(
      `SELECT setval(pg_get_serial_sequence('${t}', 'id'), COALESCE((SELECT MAX(id) FROM "${t}"), 1), (SELECT MAX(id) IS NOT NULL FROM "${t}"))`
    );
    console.log(`  ${t}: sequence set to ${r.rows[0].setval}`);
  }

  console.log('\n=== VERIFICATION (zero-loss check) ===');
  let allOk = true;
  for (const [t, info] of Object.entries(manifest)) {
    const { rows } = await client.query(`SELECT COUNT(*)::int AS n FROM "${t}"`);
    const n = rows[0].n;
    const ok = n === info.count;
    if (!ok) allOk = false;
    console.log(`  ${t}: DB=${n}  source=${info.count}  ${ok ? 'OK' : '*** MISMATCH ***'}`);
  }
  console.log(allOk ? '\nAll tables migrated with ZERO LOSS. ✓' : '\n!!! MISMATCH FOUND — do not continue without fixing !!!');
  await client.end();
  if (!allOk) process.exit(1);
}

main().catch((e) => { console.error('Import failed:', e.message); process.exit(1); });